### ISSUE TITLE
Ability to run on both - Linux and Windows

### ISSUE THREAD

**Issue by dimsanius** [Meru3m/virtualbox-snapshotter#16]
It would be a good idea to ensure script compatibility with Linux (Linux as a host).

Currently, `requirements.txt` contains `pywin32==306` Python module, which prevents installation on Linux based machines. Maybe, there are any other issues that would prevent running this script on Linux machines.

**Comment by mattiabaldari** [comment]
I totally agree on this, I remember there was some issue in doing so, but I'll try to figure out if it is doable.

**Comment by dimsanius** [comment]
My setup:
Windows host PC running Linux VM, where I have another VirtualBox installed.

I tried running the script from inside a Linux VM and am getting:
```
Traceback (most recent call last):
  File "/home/dmitrij/dev/virtualbox-snapshotter/.venv/lib/python3.10/site-packages/virtualbox/library_base.py", line 209, in _call_method
    ret = method(*in_params)
  File "<XPCOMObject method 'takeSnapshot'>", line 3, in takeSnapshot
xpcom.Exception: 0x80bb0002 (Cannot take a live snapshot of a virtual machine unless it is running.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmitrij/dev/virtualbox-snapshotter/virtualbox_snapshotter.py", line 385, in <module>
    main()
  File "/home/dmitrij/dev/virtualbox-snapshotter/virtualbox_snapshotter.py", line 282, in main
    vm_status = create_snapshot(virtual_machine, session)
  File "/home/dmitrij/dev/virtualbox-snapshotter/virtualbox_snapshotter.py", line 142, in create_snapshot
    process, _ = session.machine.take_snapshot(snap_name, description, False)
  File "/home/dmitrij/dev/virtualbox-snapshotter/.venv/lib/python3.10/site-packages/virtualbox/library.py", line 17842, in take_snapshot
    (progress, id_p) = self._call("takeSnapshot", in_p=[name, description, pause])
  File "/home/dmitrij/dev/virtualbox-snapshotter/.venv/lib/python3.10/site-packages/virtualbox/library_base.py", line 200, in _call
    return self._call_method(method, in_p=in_p)
  File "/home/dmitrij/dev/virtualbox-snapshotter/.venv/lib/python3.10/site-packages/virtualbox/library_base.py", line 228, in _call_method
    raise errobj
virtualbox.library.VBoxErrorInvalidVmState: 0x80bb0002 (Cannot take a live snapshot of a virtual machine unless it is running.)
```
It does not work on Linux. And seems like it is some kind of `virtualbox` or `vboxapi` (known as SDK) issue.

However, I found a bigger thing - it seems that `virtualbox` ([link](https://pypi.org/project/virtualbox/)) and `pyvbox` ([link](https://pypi.org/project/pyvbox/)) is basically [the same thing](https://github.com/sethmlarson/virtualbox-python). And the issue is - it is archived. So, this project relies on a library that is deprecated.

I think the way forward would be to drop `virtualbox` module dependency in order to use [VBoxManage](https://www.virtualbox.org/manual/ch08.html). VBoxManage is available for both - Linux and Windows natively after install of VirtualBox application as a whole. This way, this project can get rid of outdated `virtualbox` Python module and be up to date with VirtualBox package.

**Comment by mattiabaldari** [comment]
Hi @dimsanius, if that's the case then I totally agree with you.
If we drop that dependency it means we need to rebuild the integration with VBoxManage from scratch.
Maybe I got it wrong, but it wasn't the purpose of the the python-virtualbox library?

If I am not wrong, maybe we could just try to update that library by our own in order to have an update API, instead that embedding it into this side project. What you think?

**Comment by dimsanius** [comment]
By the looks of it, `virtualbox-python` main idea is to abstract away lots of commands available in VirtualBox SDK. Ultimately, it is VirtualBox SDK that interfaces with VirtualBox Engine. So, the issue I see is when VirtualBox SDK going to get an update, there will be no implementation of such command within `virtualbox-python`. However, not like we need it - `virtualbox-python` will hold us back only when VirtualBox SDK gets an update to one of the core commands this project relies upon. Will it happen? Nobody knows.

However, I am coming from slightly a different angle - VirtualBox SDK and `virtualbox-python` modules seem to struggle to work on all platforms. However, `VBoxManage` works quite well and is managed by Oracle themselves. So, by switching to `VBoxManage`: 
- it will bring a benefit of being always managed because it is a part of the VirtualBox main  distribution package which is manged by Oracle themselves
- it will be much more convenient to make script in this repo platform-independent. According to my tests on Win and Linux platforms, `VBoxManage` works well on both and has the same set of commands available on both platforms.

There is another options as you mentioned - either embed `virtualbox-python` required modules within this project or take full ownership of `virtualbox-python` project. For now, I am unsure if I want to do that.

I think the best way forward would be as following:
- This project works and does so well for now. There is no point in worrying about it now.
- I can fork away from your project and remove `virtualbox-python` dependency and implement `VBoxManage` instead.

This gives us best of both worlds - this project lives and can be used until it does not work. Whenever this project stops working for any reason (most likely reason will be `virtualbox-python` being incompatible with newer versions of VirtualBox SDK. I have doubts that `virtualbox-python` will ever receive support - it had already not been updated for 3 years), there will be a fork that should work. If you would want, we will be able to merge it back to this project. What do you think?

**Comment by mattiabaldari** [comment]
@dimsanius I think there are not flaws in your plan 😄.
Let's fork and manage the new project on your side.

We'll need to discuss HOW to implement the code using VBoxManage, but this is another story.
